const express = require("express");
const router = express.Router();
const AuthRouter = require("./auth.route");
const TourRouter = require("./tour.route");
const TypeTourRouter = require("./typeTour.route");
const TravelTourRouter = require("./travel_tour.route");
const LocationRouter = require("./location.route");
const ServiceRouter = require("./service.route");
const UserRouter = require("./user.route");
const Customer = require("./customer.route");
const PaymentCardRouter = require("./paymentCard.route");
const NotificationRouter = require("./notification.route");
const PostExperienceRouter = require("./postExperience.route");
const FeedbackRouter = require("./feedback.route");
const RestaurantBookingRouter = require("./restaurantBooking.route");
const HotelBookingRouter = require("./hotelBooking.route");
const VehicleBookingRouter = require("./vehicleBooking.route");
const BookingRouter = require("./booking.route");
const ProgramDiscountRouter = require("./programDiscount.route");
const DiscountServiceRouter = require("./discountService.route");
const TravelGuideRouter = require("./travelGuide.route");
const GuideTourRouter = require("./guideTour.route");
const VoucherRouter = require("./voucher.route");
const TourActivitiesRouter = require("./tourActivities.route");
const TourServiceRouter = require("./tour_service.route");
const TopicRouter = require("./topic.route");
const ArticleRouter = require("./article.route");
const DirectoryRouter = require("./directory.route");
const PassengerRouter = require("./passenger.route");
const ChatBotRouter = require("./chatbot.route");
const PaymentRouter = require("./payment.route");

router.use("/auth", AuthRouter);
router.use("/tour", TourRouter);
router.use("/type-tour", TypeTourRouter);
router.use("/location", LocationRouter);
router.use("/service", ServiceRouter);
router.use("/travel-tour", TravelTourRouter);
router.use("/user", UserRouter);
router.use("/customer", Customer);
router.use("/payment-card", PaymentCardRouter);
router.use("/notification", NotificationRouter);
router.use("/post-experience", PostExperienceRouter);
router.use("/feedback", FeedbackRouter);
router.use("/restaurant-booking", RestaurantBookingRouter);
router.use("/hotel-booking", HotelBookingRouter);
router.use("/vehicle-booking", VehicleBookingRouter);
router.use("/booking", BookingRouter);
router.use("/program-discount", ProgramDiscountRouter);
router.use("/discount-service", DiscountServiceRouter);
router.use("/travel-guide", TravelGuideRouter);
router.use("/guide-tour", GuideTourRouter);
router.use("/voucher", VoucherRouter);
router.use("/tour-activities", TourActivitiesRouter);
router.use("/tour-service", TourServiceRouter);
router.use("/topic", TopicRouter);
router.use("/article", ArticleRouter);
router.use("/directory", DirectoryRouter);
router.use("/passenger", PassengerRouter);
router.use("/chatbot", ChatBotRouter);
router.use("/payment", PaymentRouter);
module.exports = router;
